name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the version if needed

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Add SONAR_TOKEN to your GitHub secrets
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=<your_project_key> \
            -Dsonar.organization=<your_organization> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
